sudo: false
language: node_js
node_js:
  - "6"
services:
  - mongodb
env:
  - NODE_ENV=test CXX=g++-4.8
before_script:
  - npm run setup
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
